---
title: "BCN NAFLD scData, plus Hildreth adipose tissue samples (CD45+ and CD45-) et al. - Preprocessing"
author: "Hilmar Berger"
output: 
 html_document:
    toc: true
    toc_depth: 3
    toc_float: false
    number_sections: true
    code_folding: hide
    
pdf_document:
    fig_caption: true
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
---

```{r, message=FALSE}
library(Seurat)
library(ggplot2)

library(readxl)
library(knitr)
library(data.table)
library(cowplot)

library(pheatmap)

library(future)
plan("multisession", workers = 4)
options(future.globals.maxSize = 10*2**32)

data_storage_folder = file.path("./Results/data_storage","2022-05-23")
if (!file.exists(data_storage_folder)) dir.create(data_storage_folder, recursive=T)

```

```{r}
reload_data = F
if(reload_data) {
  load(file.path("Results/data_storage/2021-05-31", "All_Filtered_scData.Rdata"))

  #all_ge_data_filtered = subset(all_ge_data_filtered, cells = sel_cells)

  table(all_ge_data_filtered$sample_id_final)
}
```


```{r}
if(reload_data) {
  hildreth_env <- new.env()
  load("../../DataSets/GSE155960_Hildreth_Adipose/Analysis/Results/data_storage/2022-05-16/All_Filtered_scData.Rdata", hildreth_env)
  sc_cd45_pbmc = get("all_ge_data_filtered", hildreth_env)
  
  #sel_cells = WhichCells(sc_adult_pancreas, expression = patient_ID %in% c("AGBR024"))
  #sc_adult_pancreas = subset(sc_adult_pancreas, cells = sel_cells)

  sc_cd45_pbmc@meta.data$orig.ident = sc_cd45_pbmc$orig.ident
  sc_cd45_pbmc <- RenameCells(sc_cd45_pbmc, add.cell.id = "Hildreth")
}
```

```{r}
if(reload_data) {
  genes_NAFLD = rownames(all_ge_data_filtered@assays$RNA@counts)
  genes_hildreth = rownames(sc_cd45_pbmc@assays$RNA@counts)

  genes_shared = intersect(genes_NAFLD, genes_hildreth)

  meta_cols_NAFLD = colnames(all_ge_data_filtered@meta.data)
  meta_cols_hildreth = colnames(sc_cd45_pbmc@meta.data)

  shared_cols = intersect(meta_cols_NAFLD, meta_cols_hildreth)

  sc_cd45_pbmc@meta.data$DS = "Hildreth"
  all_ge_data_filtered@meta.data$DS = "NAFLD_BCN"

  for (cc in meta_cols_NAFLD[!meta_cols_NAFLD %in% shared_cols]) {
      sc_cd45_pbmc = AddMetaData(sc_cd45_pbmc, NA, col.name=cc)
  }

  for (cc in meta_cols_hildreth[!meta_cols_hildreth %in% shared_cols]) {
      all_ge_data_filtered = AddMetaData(all_ge_data_filtered, NA, col.name=cc)
  }

  combined_sc_data = merge(subset(all_ge_data_filtered, features = genes_shared), subset(sc_cd45_pbmc, features = genes_shared))
}

```


# Final preprocessing

Since there are several independent batches of samples with partially very different outcomes in terms of processing quality and cell viability we will use data set integration (Stuart and Butler et al., Cell 2019, doi: 10.1016/j.cell.2019.05.031) as implemented in Seurat v3.


```{r}
split_data_file = "BCN_NAFLD_Hildreth_complete_preprocessing_split_data.Rdata"
if(reload_data) {
  sc.list <- SplitObject(combined_sc_data, split.by = "orig.ident")

  sc.list <- lapply(X = sc.list, FUN = function(x) {
      x <- NormalizeData(x)
      x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
  })

  # for (i in names(sc.list)) {
  #     sc.list[[i]] <- SCTransform(sc.list[[i]], verbose = FALSE)
  # }
  sc.features <- SelectIntegrationFeatures(object.list = sc.list)
  sc.list <- lapply(X = sc.list, FUN = function(x) {
    x <- ScaleData(x, features = sc.features, verbose = FALSE)
    x <- RunPCA(x, features = sc.features, verbose = FALSE)
  })
  
  save(sc.list, sc.features, file=file.path(data_storage_folder, split_data_file ) )
} else {
  load(file.path(data_storage_folder, split_data_file))
}
```


```{r}
if(reload_data) {
  #reference_dataset <- which(names(sc.list) == "GSM4041153_healthy_CD45+")
  #sc.anchors = FindIntegrationAnchors(object.list = sc.list, dims = 1:20, reference= reference_dataset)
  sc.anchors = FindIntegrationAnchors(object.list = sc.list, anchor.features = sc.features, reduction = "rpca")
  gc()
  scData.combined <- IntegrateData(anchorset = sc.anchors)
  gc()  
}

```


<!-- ```{r} -->
<!-- reference_dataset <- which(names(sc.list) == "AGBR024_tail") -->

<!-- sc.anchors <- FindIntegrationAnchors(object.list = sc.list, normalization.method = "SCT",  -->
<!--     anchor.features = sc.features, reference = reference_dataset) -->
<!-- scData.combined <- IntegrateData(anchorset = sc.anchors, normalization.method = "SCT") -->

<!-- ``` -->


```{r}
final_data_file = file.path(data_storage_folder, "BCN_NAFLD_and_Hildreth_complete.combined.RData")

if(reload_data) {
  DefaultAssay(scData.combined) <- "integrated"
  all.genes <- rownames(scData.combined)
  scData.combined <- ScaleData(scData.combined, verbose = TRUE, features = all.genes)
  gc()
  scData.combined <- RunPCA(scData.combined, npcs = 30, verbose = TRUE)
  gc()
  
  scData.combined <- RunUMAP(scData.combined, reduction = "pca", dims = 1:30)
  scData.combined <- FindNeighbors(scData.combined, reduction = "pca", dims = 1:30)
  scData.combined <- FindClusters(scData.combined, resolution = 0.5)  
  
  save(scData.combined, file=final_data_file)
  
} else {
  load(final_data_file)
}
```

# Global clusters

```{r, fig.width=14}
DimPlot(scData.combined, reduction = "umap", group.by = "orig.ident")

p1 <- DimPlot(scData.combined, reduction = "umap", group.by = "DS")
p2 <- DimPlot(scData.combined, reduction = "umap", label = TRUE)
plot_grid(p1, p2)

DimPlot(scData.combined, reduction = "umap", split.by = "orig.ident", label = T)
```

## Cluster assignments

```{r}
m = table(scData.combined@meta.data$seurat_clusters, scData.combined@meta.data$orig.ident)
kable(m)
```


```{r, fig.height=10, fig.width=8}
mm = as.matrix.data.frame(m)
colnames(mm) = colnames(m)
rownames(mm) = rownames(m)
mm_rel = sweep(mm, 2, apply(mm, 2,sum), "/")
pheatmap(mm_rel, main="Relative single cell contribution of each cluster to condition totals")
```

```{r}
old_labels = read.table("Metadata_complete.txt", sep="\t", header=T, stringsAsFactors = F)
rownames(old_labels) = old_labels$orig_cell_id

scData.combined@meta.data$labels_wCD45pos_only = NA
scData.combined@meta.data$labels_wCD45pos_only = old_labels[scData.combined$orig_cell_id, "cluster_label"]

table(scData.combined$labels_wCD45pos_only, scData.combined$seurat_clusters)
```

```{r}
old_labels_hildreth = read.table("../../DataSets/GSE155960_Hildreth_Adipose/Analysis/Metadata_Hildreth_no_integration.txt", sep="\t", header=T, stringsAsFactors = F)
rownames(old_labels_hildreth) = paste0("Hildreth_",old_labels_hildreth$cell_id)

scData.combined@meta.data$labels_hildreth = NA
scData.combined@meta.data$labels_hildreth = old_labels_hildreth[Cells(scData.combined), "cluster_label"]

table(scData.combined$labels_hildreth, scData.combined$seurat_clusters)

```


# Software versions

```{r}
sessionInfo()
```

