---
title: "Pseudotime estimation, BCN Adipose Tissue + Hildreth adipose tissue cells - myeloid clusters only"
author: "Hilmar Berger"
output: 
 html_document:
    toc: true
    toc_depth: 3
    toc_float: false
    number_sections: true
    code_folding: hide
    
pdf_document:
    fig_caption: true
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
---


```{r, message=FALSE}
rm(list=ls())
library(Seurat)
library(ggplot2)

library(readxl)
library(writexl)
library(knitr)
library(data.table)
library(cowplot)

library(pheatmap)

#library(monocle)
library(slingshot)
library(RColorBrewer)
library(scales)

result_folder = paste("./Results",format(Sys.time(), "%Y-%m-%d"),sep="/")
if (!file.exists(result_folder)) dir.create(result_folder, recursive=T)

data_storage_folder = file.path("./Results/data_storage","2022-05-23")
if (!file.exists(data_storage_folder)) dir.create(data_storage_folder, recursive=T)

library(future)
options("future.globals.maxSize"=2**33)
plan("multisession", workers = 8)

rerun_analyses = T
```

```{r, message=FALSE, warning=FALSE}
load(file.path(data_storage_folder,"scData_NAFLD_Hildreth_complete_MoMF.DC.cluster_annotated.RData"))
scData.combined = scData_MoMF.DC
rm(scData_MoMF.DC)
invisible(gc())
```

```{r, fig.width=10}
DimPlot(scData.combined, group.by = "cluster_label", label=T) + NoLegend()
```


```{r}
scData.combined <- SetIdent(scData.combined, value="seurat_clusters")
sds = as.SingleCellExperiment(scData.combined, assay = "RNA")
sds$seurat_clusters = as.character(sds$seurat_clusters)
sds$cluster_label = as.character(sds$cluster_label)

```

```{r}
root_cluster = "Classical Monocytes/MoMF 1b"
#root_cluster = "Perivascular MF 1"
tmp = as.data.frame(unique(colData(sds)[, c("cluster_label","seurat_clusters")]))
root_cluster_id = as.character(subset(tmp, cluster_label==root_cluster)$seurat_clusters)
# NOTE: Slingshot will not always respect the provided root cluster, and sometimes will choose a root cluster on its own without warning
```

# Slingshot trajectory analysis


```{r}
sds <- slingshot(sds, clusterLabels = "seurat_clusters", reducedDim = "UMAP", start.clus = root_cluster_id, stretch = 0)
```


```{r}
cell_pal <- function(cell_vars, pal_fun,...) {
  if (is.numeric(cell_vars)) {
    pal <- pal_fun(100, ...)
    return(pal[cut(cell_vars, breaks = 100)])
  } else {
    categories <- sort(unique(cell_vars))
    pal <- setNames(pal_fun(length(categories), ...), categories)
    return(pal[cell_vars])
  }
}
```

```{r}
cell_colors <- cell_pal(sds$cluster_type, brewer_pal("qual", "Set3"))
cell_colors_clust <- cell_pal(sds$seurat_clusters, hue_pal())
```

```{r, echo=FALSE, eval=FALSE}
lnes <- getLineages(reducedDim(sds,"UMAP"), sds$seurat_clusters)
slingLineages(lnes)

```


## Minimum spanning tree

```{r}
plot(reducedDim(sds, "UMAP"), col = cell_colors_clust, pch = 16, cex = 0.5)
lines(SlingshotDataSet(sds), lwd = 2, type = 'lineages', col = 'black')
```


```{r, eval=FALSE}
plot(reducedDim(sds, type = "UMAP"), col = cell_colors, pch = 16, cex = 0.5)
lines(SlingshotDataSet(sds), lwd = 2, type = 'lineages', col = 'black')
```



## Inferred lineages

### Fixed root cluster

We here have set the root to cluster `r root_cluster`. 

```{r}
plot(reducedDim(sds, "UMAP"), col = cell_colors_clust, pch = 16, cex = 0.5)
lines(SlingshotDataSet(sds), lwd = 2, col = 'black')
```


### Free root cluster

In this analysis the root cluster will be automatically defined by Slingshot. 

```{r}
sds_free_root <- slingshot(sds, clusterLabels = "seurat_clusters", reducedDim = "UMAP", stretch = 0, extend="n")
```

```{r}
plot(reducedDim(sds_free_root, "UMAP"), col = cell_colors_clust, pch = 16, cex = 0.5)
lines(SlingshotDataSet(sds_free_root), lwd = 2, col = 'black')
```



# Temporally dynamic genes

```{r}
library(tradeSeq)
# library(SingleCellExperiment)

# sce = SingleCellExperiment(assays=List(counts = scData.combined@assays$RNA@counts, norm=scData.combined@assays$RNA@data), reducedDims = List(UMAP=Embeddings(scData.combined,"umap")))
# colData(sce)$GMM <- scData.combined$seurat_clusters
#
# sce = slingshot(sce, clusterLabels="GMM", reducedDim="UMAP")

# fit negative binomial GAM

if(rerun_analyses) {
  library(BiocParallel)
  bp_param = MulticoreParam(workers = 8)
  #bp_param = SnowParam(workers = 8)
  
  #set.seed(5)
  #icMat <- evaluateK(counts = scData.combined@assays$RNA@counts, sds = PseudotimeOrdering(sds), k = 3:10, nGenes=200, verbose=T)
  
  sds <- fitGAM(sds, BPPARAM=bp_param, parallel = T)
  
  # test for dynamic expression
  ATres <- associationTest(sds)

  save(sds, ATres, file=file.path(data_storage_folder, "Slingshot_AT_with_Hildreth.Rdata") )  
} else {
  load("Slingshot_AT_with_Hildreth.Rdata")   
}
```

```{r}
topgenes <- rownames(ATres[order(ATres$pvalue), ])[1:250]
pst.ord <- order(sds$slingPseudotime_1, na.last = NA)
heatdata <- assays(sds)$counts[topgenes, pst.ord]
heatclus <- sds$GMM[pst.ord]

heatmap(log1p(heatdata), Colv = NA,
        ColSideColors = brewer.pal(9,"Set1")[heatclus])
```

